

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
   sh "flutter clean"
   sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
   firebase_app_distribution(
            app: "1:274679670921:android:48b251bbf3da89ce49fe58",
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            testers: "tester1@company.com, tester2@company.com",
            android_artifact_type:"APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            release_notes: "First Fastlane Firebase Distribution Test"
        )  
  end
end
